In [1]:
#importing numpy
import numpy as np

#Create Arrays
arr1 = np.array([10,20,30,40,50,60,70])
arr2 = np.array((1,2,3,4,5,6))

print(arr1)
print(arr2)

#Array Properties
print('Dimensions= ',arr1.ndim)
print('Shape= ',arr1.shape)
print('Size= ',arr1.size)
print('Data Type= ',arr1.dtype)

#Indexing and Slicing
print(arr1[0])
print(arr1[-1])
print(arr1[:2])
print(arr1[3:])
print(arr1[1:4])

#Mathematical operations
arr = np.array([10,20,30,40,50])

print(arr + 10)
print(arr - 5)
print(arr * 2)
print(arr / 5)
print(arr ** 2)

#Statistical Function
marks = np.array([65,75,80,56,78])

print('Sum= ',np.sum(marks))
print('Average= ',np.mean(marks))
print('Maximum= ',np.max(marks))
print('Minimum= ',np.min(marks))
print('Standard Deviation= ',np.std(marks))

#Reshaping
arr = np.array([1,2,3,4,5,6])

matrix = arr.reshape(2,3)

print(matrix)

#2D Array
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(matrix)
print("Element at row 1, column 2 =", matrix[0][1])
print("First row =", matrix[0, :])
print("Second column =", matrix[:, 1])

#Mini Project ( Analyzing Students Marks )
marks = np.array([68,78,79,57,97,64,87,65,68,78,79,57,97,64,87,65])

print('Total Students= ',marks.size)
print('Maximum Marks= ',np.max(marks))
print('Minimum Makrs= ',np.min(marks))
print('Average Marks= ',np.mean(marks))
print('Marks in ascending order= ',np.sort(marks))
print('Marks in decending order= ',np.sort(marks)[::-1])
print('Students scoring above 75 marks= ',marks[marks>75])
print('Students scoring below 75 marks= ',marks[marks<75])

[10 20 30 40 50 60 70]
[1 2 3 4 5 6]
Dimensions=  1
Shape=  (7,)
Size=  7
Data Type=  int64
10
70
[10 20]
[40 50 60 70]
[20 30 40]
[20 30 40 50 60]
[ 5 15 25 35 45]
[ 20  40  60  80 100]
[ 2.  4.  6.  8. 10.]
[ 100  400  900 1600 2500]
Sum=  354
Average=  70.8
Maximum=  80
Minimum=  56
Standard Deviation=  9.019977827023745
[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 1, column 2 = 2
First row = [1 2 3 4]
Second column = [ 2  6 10]
Total Students=  16
Maximum Marks=  97
Minimum Makrs=  57
Average Marks=  74.375
Marks in ascending order=  [57 57 64 64 65 65 68 68 78 78 79 79 87 87 97 97]
Marks in decending order=  [97 97 87 87 79 79 78 78 68 68 65 65 64 64 57 57]
Students scoring above 75 marks=  [78 79 97 87 78 79 97 87]
Students scoring below 75 marks=  [68 57 64 65 68 57 64 65]
